version: '2'

volumes:
  database:
    external:
      name: "database_${PROJECT_NAME}"

services:
  webserver:
    build: ./apache${PHP_VERSION}
    volumes:
      - ${DOCUMENT_ROOT}:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./000-default.conf:/etc/apache2/sites-available/000-default.conf
    links:
      - mysql:mysql
    env_file:
      - ./../../../../.env
    environment:
      - VIRTUAL_HOST=${PROJECT_NAME}.localhost
    networks:
      - proxynet

  mysql:
    build: ./mysql
    volumes:
      - database:/var/lib/mysql
    networks:
      - proxynet

  adminer:
    build: ./adminer
    links:
      - mysql:mysql
    environment:
      - VIRTUAL_HOST=adminer.${PROJECT_NAME}.localhost
    networks:
      - proxynet

networks:
  proxynet:
    external: true