version: '2'

volumes:
  database:
    external:
      name: "database_${PROJECT_NAME}"

services:
  webserver:
    container_name: ${PROJECT_NAME}_webserver_1
    build: ./apache${PHP_VERSION}
    volumes:
      - ./../../../../:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./000-default.conf:/etc/apache2/sites-available/000-default.conf
    links:
      - mysql:mysql
      - blackfire:blackfire
      - chrome
    depends_on:
      - chrome
    env_file:
      - ./../../../../.env
    environment:
      - VIRTUAL_HOST=${PROJECT_NAME}.local
      - PHP_IDE_CONFIG=serverName=localhost
    networks:
      - proxynet

  mysql:
    container_name: ${PROJECT_NAME}_mysql_1
    build: ./mysql
    volumes:
      - database:/var/lib/mysql
    networks:
      - proxynet

  mysql_test:
    container_name: ${PROJECT_NAME}_mysql_test_1
    build: ./mysql
    networks:
      - proxynet
    tmpfs:
      - /var/lib/mysql/:rw,noexec,nosuid,size=600m
      - /tmp/:rw,noexec,nosuid,size=50m

  adminer:
    container_name: ${PROJECT_NAME}_adminer_1
    build: ./adminer
    links:
      - mysql:mysql
    environment:
      - VIRTUAL_HOST=adminer.${PROJECT_NAME}.local
    networks:
      - proxynet

  blackfire:
    container_name: ${PROJECT_NAME}_blackfire_1
    image: blackfire/blackfire
    environment:
      - BLACKFIRE_SERVER_ID=${BLACKFIRE_SERVER_ID}
      - BLACKFIRE_SERVER_TOKEN=${BLACKFIRE_SERVER_TOKEN}
    networks:
      - proxynet

  chrome:
    image: selenium/standalone-chrome
    extra_hosts:
      - "${PROJECT_NAME}.local:172.18.0.1"
    networks:
      - proxynet
    volumes:
      - /dev/shm:/dev/shm

networks:
  proxynet:
    external: true