version: '2'

services:
  webserver:
#    build: ./apache5 # PHP 5.6
    build: ./apache
    volumes:
      - ./../../../../:/var/www/html
      - ./data/apache:/var/log/apache2
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./000-default.conf:/etc/apache2/sites-available/000-default.conf
    links:
      - mysql:mysql
    environment:
      - VIRTUAL_HOST=localhost
      - PHP_IDE_CONFIG=serverName=localhost
    networks:
      - proxynet

  mysql:
    build: ./mysql
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./data/mysql-tmp:/tmp/mysql
    networks:
      - proxynet

  adminer:
    build: ./adminer
    links:
      - mysql:mysql
    environment:
      - VIRTUAL_HOST=adminer.dev
    networks:
      - proxynet

networks:
  proxynet:
    external: true